collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6898496
color:
  saturation: 0.6696481
  brandStrength: 0.7424812
  rhythmicContrast: 0.6874354
  brandColors:
    - '#CDD9CE'
    - '#384140'
    - '#0E0F0E'
    - '#666E6E'
    - '#91999B'
  lightness: 0.8991765
layout_spectrum: 0.4266917
name: Modular
